# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chatgpt
    ports:
      - "5432:5432"
  
  chatgpt-api-nest:
    image: erohal/chatgpt-api-nest
    restart: always
    environment:
      DATABASE_URL: postgresql://root:root@db:5432/chatgpt?schema=public
      JWT_SECRET: iloveyoubaby
      OPENAI_BASE_URL: https://api.openai.com
      OPENAI_INIT_KEY: 
    ports:
      - "3000:3000"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080