version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chatgpt
      TZ: Asia/Shanghai
    volumes:
      - /var/lib/postgresql/data
  
  service:
    image: chatgpt-api-nest
    restart: always
    environment:
      - TZ: Asia/Shanghai
      - DATABASE_URL: "postgresql://root:root@db:5432/chatgpt?schema=public"
      - OPENAI_BASE_URL: https://api.openai.com
      - OPENAI_INIT_KEY: "sk-ZZZZXXXXIIIIOOOOUUUUT3BlbkFJUj3WkGPPPP0JW67RQQQQ"
      - JWT_SECRET: iloveyoubaby
    ports:
      - 3000:3000
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080